#!/usr/bin/env python3
"""
gen-report.py — Generate writeup/report from workspace/active/session.md
Usage: python3 gen-report.py [session_file] [--type ctf|lab|ir]
"""

import sys
import os
import re
from datetime import date

SESSION_FILE = sys.argv[1] if len(sys.argv) > 1 else "workspace/active/session.md"
REPORT_TYPE = "ctf"
for arg in sys.argv:
    if arg.startswith("--type="):
        REPORT_TYPE = arg.split("=")[1]
    elif arg in ("ctf", "lab", "ir", "malware"):
        REPORT_TYPE = arg

def read_session(path: str) -> dict:
    if not os.path.exists(path):
        print(f"[-] Session file not found: {path}")
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    data = {}
    # Extract key: value pairs from markdown
    for line in content.splitlines():
        if ":" in line and line.startswith("-") or line.startswith("**"):
            clean = line.strip("- *").strip()
            if ":" in clean:
                k, _, v = clean.partition(":")
                data[k.strip().lower()] = v.strip()

    data["_raw"] = content
    return data

def gen_ctf_writeup(s: dict) -> str:
    name = s.get("name", "Unknown Challenge")
    category = s.get("category", "Web")
    today = date.today().isoformat()

    # Extract findings from raw content
    raw = s.get("_raw", "")

    return f"""# CTF Writeup — {name}

**Category:** {category}
**Date:** {today}

---

## TL;DR
[สรุป 1-2 ประโยค: vulnerability คืออะไร exploit ยังไง]

---

## Reconnaissance
{extract_section(raw, "Recon|Reconnaissance|Phase 1")}

---

## Enumeration
{extract_section(raw, "Enum|Enumeration|Phase 2")}

---

## Exploitation
{extract_section(raw, "Exploit|Exploitation|Phase 3")}

---

## Post-Exploitation / Privilege Escalation
{extract_section(raw, "PrivEsc|Post-Exploit|Phase 4")}

---

## Flags
{extract_section(raw, "Flag|Flags")}

---

## Lessons Learned
- [concept ที่ได้เรียนรู้]
- [tool หรือ technique ใหม่]
- [pattern ที่ควรจำ]

---
*Generated by Cyber AI OS — gen-report.py*
"""

def gen_lab_report(s: dict) -> str:
    name = s.get("name", "Unknown Lab")
    target = s.get("target_ip", s.get("target", "Unknown"))
    today = date.today().isoformat()
    raw = s.get("_raw", "")

    return f"""# Lab Report — {name}

**Target:** {target}
**Date:** {today}

---

## Executive Summary
[สรุปสั้นๆ สำหรับ non-technical: เจอ vulnerability อะไร impact ระดับไหน]

---

## Methodology
Recon → Enumeration → Exploitation → Post-Exploitation

---

## Findings

### Finding 1: [Title]
**Severity:** Critical / High / Medium / Low
**Component:** [Service/Port]

**Description:** [อธิบาย vulnerability]

**Evidence:**
```
{extract_section(raw, "Finding|Exploit|Evidence")}
```

**Impact:** [ผลกระทบ]

**Remediation:** [วิธีแก้]

---

## Proof of Compromise
{extract_section(raw, "Flag|Root|Proof")}

---
*Generated by Cyber AI OS — gen-report.py*
"""

def gen_ir_report(s: dict) -> str:
    incident = s.get("incident_type", "Unknown")
    host = s.get("hostname", "Unknown")
    today = date.today().isoformat()
    raw = s.get("_raw", "")

    return f"""# Incident Response Report

**Incident Type:** {incident}
**Affected Host:** {host}
**Report Date:** {today}

---

## Executive Summary
[2-3 ประโยค: เกิดอะไรขึ้น ผลกระทบ และ action ที่ทำไป]

---

## Timeline
{extract_section(raw, "Timeline|Phase")}

---

## Root Cause Analysis
[Initial vector คืออะไร ทำไมถึงเกิด]

---

## Impact Assessment
- Systems affected:
- Data at risk:
- Services disrupted:

---

## Containment & Eradication Actions
{extract_section(raw, "Contain|Eradicat|Action")}

---

## Lessons Learned
- Detection gap:
- Prevention:
- Process improvement:

---
*Generated by Cyber AI OS — gen-report.py*
"""

def extract_section(raw: str, pattern: str) -> str:
    lines = raw.splitlines()
    capture = False
    result = []
    regex = re.compile(pattern, re.IGNORECASE)

    for line in lines:
        if regex.search(line) and line.startswith("#"):
            capture = True
            continue
        if capture and line.startswith("#") and not regex.search(line):
            break
        if capture:
            result.append(line)

    return "\n".join(result).strip() or "[ยังไม่มีข้อมูล — เพิ่มใน session.md]"

def main():
    print(f"[*] Reading: {SESSION_FILE}")
    s = read_session(SESSION_FILE)

    generators = {
        "ctf": gen_ctf_writeup,
        "lab": gen_lab_report,
        "ir": gen_ir_report,
    }

    gen_fn = generators.get(REPORT_TYPE, gen_ctf_writeup)
    report = gen_fn(s)

    name = s.get("name", "report").lower().replace(" ", "-")
    outfile = f"workspace/outputs/{name}-{REPORT_TYPE}-report.md"
    os.makedirs("workspace/outputs", exist_ok=True)

    with open(outfile, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"[+] Report generated: {outfile}")
    print(f"\n--- Preview ---\n{report[:500]}...")

if __name__ == "__main__":
    main()
